language: node_js
node_js:
  - 12
before_install:
  - 'echo -e "@before_install"'
  - npm install -g beamup-cli
  - npm install -g codecov
install:
  - 'echo -e "@install"'
before_script:
  - 'echo -e "@before_script"'
script:
  - 'echo -e "@script"'
  - codecov # upload coverage reports to codecov.io
  - beamup # deploying to the BeamUp servers
after_success:
  - 'echo -e "@after_success"'
after_script:
  - 'echo -e "@after_script"'
notifications:
  email:
    on_success: change
    on_failure: always
